### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 24: invalid continuation byte

### ISSUE THREAD

**Issue by chenll7** [MorganZhang100/line-counter#2]
bear@BEAR-PC:/mnt/d/Cll/bear-public/code$ line
Search in /mnt/d/Cll/bear-public/code/
Traceback (most recent call last):
  File "/home/bear/.local/bin/line", line 11, in <module>
    sys.exit(_main())
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 232, in _main
    a.find_files(os.getcwd(), 'filtrate')
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 68, in find_files
    self.find_files(folder, 'all')
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 71, in find_files
    self.find_files(folder, 'all')
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 59, in find_files
    self.add_file(file)
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 102, in add_file
    self.final_file_dic[file] = self.analyze_file(file)
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 105, in analyze_file
    file_line_count = self.read_line_count(file)
  File "/home/bear/.local/lib/python3.6/site-packages/line.py", line 113, in read_line_count
    for file_line in open(file_name):
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 24: invalid continuation byte

**Comment by chenll7** [comment]
跑不了

**Comment by 2niuhe** [comment]
> 找到line.py文件，然后修改第113行,比如我的python3.5

```shell
sudo vim /usr/local/lib/python3.5/dist-packages/line.py 
```
113行改成：
```python
for file_line in open(file_name,'rb'):
```

**Comment by TinyHandsome** [comment]
楼上正解，windows可以找到python3.*\Lib\site-packages\line.py 打开编辑113行，加上'rb'
